[Bug Fix] Modify nav action and sim for cross-floor task
SgtVincent/habitat-lab pull request #16
Opened 2024-08-21 05:20 UTC by Tradewindycc

## Motivation and Context
Modify **BaseVelAction** and **RearrangeSim** to adapt cross-floor navigation task for **mp3d** dataset.

## How Has This Been Tested
Run the **habitat_baselines.run** with --config-name=social_rearrange/llm_spot_fetch_mobility.yaml

## Types of changes

- **\[Docs change\]** Addition or changes to the documentation
- **\[Refactoring\]** Large changes to the code that improve its functionality or performance
- **\[Dependency Upgrade\]** Upgrades one or several dependencies in habitat
- **\[Bug Fix\]** (non-breaking change which fixes an issue)
- **\[Development\]** A pull request that add new features to the [habitat-lab](/habitat-lab) task and environment codebase. Development Pull Requests must be small (less that 500 lines of code change), have unit testing, very extensive documentation and examples. These are typically new tasks, environments, sensors, etc... The review process for these Pull Request is longer because these changes will be maintained by our core team of developers, so make sure your changes are easy to understand!
- **\[Experiment\]** A pull request that add new features to the [habitat-baselines](/habitat-baselines/) training codebase. Experiments Pull Requests can be any size, must have smoke/integration tests and be isolated from the rest of the code. Your code additions should not rely on other habitat-baselines code. This is to avoid dependencies between different parts of habitat-baselines. You must also include a README that will document how to use your new feature or trainer. **You** will be the maintainer of this code, if the code becomes stale or is not supported often enough, we will eventually remove it.

## Checklist

- [x] My code follows the code style of this project.
- [x] I have updated the documentation if required.
- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] I have completed my CLA (see **CONTRIBUTING**)
- [x] I have added tests to cover my changes if required.

2024-08-23 03:18 UTC, SgtVincent requested changes

2024-08-23 03:18 UTC, SgtVincent commented on habitat-lab/habitat/datasets/rearrange/navmesh_utils.py
> +
Why do we want the largest two islands?

2024-08-23 03:18 UTC, SgtVincent commented on habitat-lab/habitat/tasks/rearrange/multi_task/pddl_sim_state.py
> +                obs = [abs_obj_id]
@Zhouxunzhe Could you please also review this part? I think you have modified this section before. Does this change affect your part?

2024-08-23 06:33 UTC, Tradewindycc commented on habitat-lab/habitat/datasets/rearrange/navmesh_utils.py
> +
Attempt to avoid collision between spot and fetch by sampling them to different islands.

2024-08-27 06:58 UTC, Tradewindycc commented on habitat-lab/habitat/datasets/rearrange/navmesh_utils.py
> +
solved.

2024-08-29 04:31 UTC, SgtVincent approved these changes
LGTM!

2024-08-29 04:31 UTC, merged